name: Build TotoX APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.7'
          channel: stable

      - name: Prepare Android
        working-directory: totox
        run: flutter create --platforms=android .

      - name: Install dependencies
        working-directory: totox
        run: flutter pub get

      - name: Build APK
        working-directory: totox
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: TotoX-APK
          path: totox/build/app/outputs/flutter-apk/app-release.apk
